import { useMemo, useState, useEffect } from "react";
import { useStudyData, type SchedulePlan } from "@/hooks/useStudyData";
import { GlassCard } from "@/components/shared/GlassCard";
import { MiniCalendar } from "@/components/dashboard/MiniCalendar";
import { format } from "date-fns";
import { Archive as ArchiveIcon, ArrowRight, BookOpen, Calendar as CalendarIcon, Flame, Settings as SettingsIcon, Target, Trophy } from "lucide-react";
import { Link } from "wouter";
import { qualifyingActivityByDay } from "@/lib/examActivity";

function daysUntil(dateStr: string) { const target = new Date(dateStr); target.setHours(0, 0, 0, 0); const today = new Date(); today.setHours(0, 0, 0, 0); return Math.round((target.getTime() - today.getTime()) / 86_400_000); }

function NextExamsSection({ plans, subjects }: { plans: SchedulePlan[]; subjects: any[] }) {
  const now = new Date(); now.setHours(0, 0, 0, 0);
  const direct = subjects.flatMap(subject => (subject.exams ?? []).filter((exam: any) => exam.date && !exam.checked).map((exam: any) => ({ id: exam.id, name: exam.name, subjectName: subject.name, date: exam.date })));
  const planned = plans.filter(plan => plan.type === "exam" && plan.source === "quickExam").flatMap(plan => plan.items.filter(item => item.date && !item.checked).map(item => ({ id: item.id, name: item.subjectName, subjectName: item.subjectName, date: item.date! })));
  const unique = new Map<string, any>(); [...direct, ...planned].forEach(item => unique.set(`${item.subjectName}-${item.name}-${item.date}`, item));
  const exams = [...unique.values()].filter(item => new Date(item.date) >= now).sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()).slice(0, 2);
  return <section className="space-y-4"><div className="flex items-center justify-between px-1"><h2 className="text-xl font-bold tracking-tight">Next Exams</h2><Link href="/schedule" className="text-sm font-semibold text-primary">View all</Link></div>{!exams.length ? <GlassCard className="flex flex-col items-center justify-center border-2 border-dashed bg-transparent p-8 text-center text-muted-foreground"><CalendarIcon className="mb-3 h-8 w-8 opacity-30" /><p className="font-medium">No upcoming exams.</p></GlassCard> : <div className="space-y-3">{exams.map((exam, index) => { const days = daysUntil(exam.date), color = days <= 3 ? "#f87171" : days <= 7 ? "#fbbf24" : "#60a5fa"; return index === 0 ? <GlassCard key={exam.id} className="relative overflow-hidden rounded-3xl border-border/60 p-5 shadow-lg" style={{ backgroundImage: `radial-gradient(circle at 92% 48%, ${color}18, transparent 40%)` }}><div className="relative flex min-w-0 items-center gap-4"><div className="min-w-0 flex-1"><p className="max-w-full break-words text-[10px] font-black uppercase leading-4 tracking-[.12em]" style={{ color }}>Next Exam · {exam.subjectName}</p><h3 className="mt-2 break-words text-lg font-bold leading-snug">{exam.name}</h3><p className="mt-3 text-xs text-muted-foreground">{format(new Date(exam.date), "EEEE, MMM d, yyyy")}</p></div><div className="flex w-16 shrink-0 flex-col items-center justify-center self-stretch text-center"><p className="text-5xl font-black leading-none" style={{ color }}>{days === 0 ? "!" : days}</p><p className="mt-1 text-[10px] font-black uppercase tracking-wider text-muted-foreground">{days === 0 ? "Today" : days === 1 ? "day" : "days"}</p></div></div></GlassCard> : <GlassCard key={exam.id} className="flex min-w-0 items-center gap-4 p-4"><div className="min-w-0 flex-1"><p className="break-words text-[10px] font-bold uppercase leading-4 tracking-widest text-muted-foreground">{exam.subjectName}</p><p className="break-words font-semibold">{exam.name}</p><p className="text-xs text-muted-foreground">{format(new Date(exam.date), "EEE, MMM d")}</p></div><b className="shrink-0" style={{ color }}>{days === 0 ? "Today" : `${days}d`}</b></GlassCard>; })}</div>}</section>;
}

function DashboardProgress({ subjects }: { subjects: any[] }) {
  const rows = subjects.map(subject => { const lectureTotal = subject.lectures.length, lectureDone = subject.lectures.filter((lecture: any) => lecture.checked).length; const finals = subject.exams.filter((exam: any) => exam.name === "Final Exam" && exam.lastScore); const finalAverage = finals.length ? finals.reduce((sum: number, exam: any) => sum + exam.lastScore.percentage, 0) / finals.length : 0; const lectureProgress = lectureTotal ? lectureDone / lectureTotal * 100 : 0; return { subject, score: Math.round((lectureProgress + finalAverage) / 2), lectureDone, lectureTotal, finals: finals.length }; });
  const overall = rows.length ? Math.round(rows.reduce((sum, row) => sum + row.score, 0) / rows.length) : 0, leader = [...rows].sort((a, b) => b.score - a.score)[0], complete = rows.reduce((sum, row) => sum + row.lectureDone, 0), total = rows.reduce((sum, row) => sum + row.lectureTotal, 0), finals = rows.reduce((sum, row) => sum + row.finals, 0);
  return <section className="space-y-4"><div className="flex items-center justify-between px-1"><div><p className="text-xs font-black uppercase tracking-[.18em] text-muted-foreground">Performance</p><h2 className="mt-1 text-2xl font-black">Your progress</h2></div><Link href="/progress" className="flex h-10 w-10 items-center justify-center rounded-full border border-primary/20 bg-primary/10 text-primary"><ArrowRight className="h-5 w-5" /></Link></div>{!subjects.length ? <GlassCard className="border-2 border-dashed bg-transparent p-8 text-center text-muted-foreground">Add subjects to see progress.</GlassCard> : <GlassCard className="overflow-hidden rounded-3xl border-border/60 p-0 shadow-lg"><div className="relative p-5" style={{ backgroundImage: 'radial-gradient(circle at 92% 18%, hsl(var(--primary) / 0.14), transparent 38%)' }}><div className="relative grid grid-cols-[6rem_minmax(0,1fr)] items-center gap-5"><div className="flex h-24 w-24 items-center justify-center rounded-full border-[9px] border-primary/20 bg-secondary/40"><div className="text-center"><p className="text-3xl font-black">{overall}%</p><p className="text-[9px] font-black uppercase tracking-wider text-muted-foreground">Overall</p></div></div><div className="min-w-0"><p className="text-xs font-bold text-primary">Study command center</p><h3 className="mt-1 break-words text-xl font-black leading-tight sm:text-2xl">{overall >= 80 ? "Excellent momentum" : overall >= 50 ? "Keep building" : "Ready to grow"}</h3><p className="mt-2 break-words text-sm text-muted-foreground">{leader ? <>Leading: <b className="text-foreground">{leader.subject.name}</b></> : "Start your first subject"}</p></div></div><div className="relative mt-5 h-3 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary transition-all duration-700" style={{ width: `${overall}%` }} /></div></div><div className="grid grid-cols-3 border-t border-border/40"><Metric icon={BookOpen} value={`${complete}/${total}`} label="Lectures" /><Metric icon={Trophy} value={String(finals)} label="Finals" /><Metric icon={Target} value={String(subjects.length)} label="Subjects" /></div></GlassCard>}</section>;
}
function Metric({ icon: Icon, value, label }: { icon: any; value: string; label: string }) { return <div className="min-w-0 border-r border-border/40 p-3 text-center last:border-r-0 sm:p-4"><Icon className="mx-auto h-5 w-5 text-primary" /><p className="mt-2 text-lg font-black">{value}</p><p className="break-words text-[9px] font-black uppercase tracking-wider text-muted-foreground">{label}</p></div>; }

function useExamStreak() {
  const [version, setVersion] = useState(0);
  useEffect(() => { const refresh = () => setVersion(value => value + 1); window.addEventListener("studyhub:exam-activity", refresh); window.addEventListener("storage", refresh); return () => { window.removeEventListener("studyhub:exam-activity", refresh); window.removeEventListener("storage", refresh); }; }, []);
  return useMemo(() => { const days = qualifyingActivityByDay(90), today = new Date(), todayKey = today.toLocaleDateString("en-CA"), todayCount = days.get(todayKey) ?? 0; if (!todayCount) return { streak: 0, todayCount, color: "#34c759", label: "No 90% exam today" }; let streak = 0, cursor = new Date(today); while ((days.get(cursor.toLocaleDateString("en-CA")) ?? 0) > 0) { streak++; cursor.setDate(cursor.getDate() - 1); } const color = todayCount >= 3 ? "#ff3b30" : todayCount === 2 ? "#ff9500" : "#ffcc00"; return { streak, todayCount, color, label: `${todayCount} qualifying exam${todayCount === 1 ? "" : "s"} today` }; }, [version]);
}

export function Dashboard() {
  const { subjects, schedule, checklist, schedulePlans } = useStudyData(); const streak = useExamStreak();
  return <div className="space-y-8 pb-12"><header className="flex items-start justify-between gap-4"><div className="flex shrink-0 items-center gap-2"><Link href="/settings" aria-label="Settings" className="flex h-11 w-11 items-center justify-center rounded-2xl border border-border/50 bg-secondary/80"><SettingsIcon className="h-5 w-5 text-muted-foreground" /></Link><Link href="/archive" aria-label="Archive" className="flex h-11 w-11 items-center justify-center rounded-2xl border border-border/50 bg-secondary/80"><ArchiveIcon className="h-5 w-5 text-muted-foreground" /></Link></div><div className="min-w-0 text-right"><h1 className="text-2xl font-black tracking-tight md:text-4xl">Hello fool 👋</h1><p className="mt-1 truncate text-sm font-medium text-muted-foreground md:text-lg">{format(new Date(), "EEEE, MMMM do")}</p></div></header><GlassCard className="relative flex w-full items-center gap-4 overflow-hidden rounded-3xl px-5 py-4" style={{ borderColor: `${streak.color}55`, background: `linear-gradient(135deg, ${streak.color}18, ${streak.color}08)` }}><div className="relative flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl border" style={{ borderColor: `${streak.color}66`, backgroundColor: `${streak.color}20`, boxShadow: `0 0 24px ${streak.color}35` }}><Flame className="h-7 w-7" style={{ color: streak.color, fill: `${streak.color}55` }} /></div><div className="min-w-0 flex-1"><p className="text-3xl font-black leading-none">{streak.streak}</p><p className="mt-2 break-words text-[10px] font-black uppercase leading-4 tracking-[.14em] text-muted-foreground">{streak.label}</p></div><div className="text-right"><p className="text-[10px] font-black uppercase tracking-[.16em]" style={{ color: streak.color }}>Day streak</p><p className="mt-1 text-xs text-muted-foreground">90%+ attempts only</p></div></GlassCard><NextExamsSection plans={schedulePlans} subjects={subjects} /><MiniCalendar schedule={schedule} checklist={checklist} /><DashboardProgress subjects={subjects} /></div>;
}
