import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, Check, ChevronLeft, ChevronRight, Clock3, RotateCcw, Sparkles, X } from "lucide-react";
import { useLocation, useRoute, useSearch } from "wouter";
import { useStudyData, getScoreBand, type ExamQuestion, type Flashcard } from "@/hooks/useStudyData";
import { GlassCard } from "@/components/shared/GlassCard";

const transition = { duration: .34, ease: [.4, 0, .2, 1] as const };
type FlashRating = "known" | "moderate" | "missed";
type MediaFlashcard = Flashcard & { frontImage?: string; backImage?: string };
type ShuffledQuestion = ExamQuestion & { originalCorrectAnswer: number };
type Item = { kind: "question"; question: ShuffledQuestion } | { kind: "flashcard"; card: MediaFlashcard };
type AnswerValue = number | FlashRating;

function shuffleQuestion(question: ExamQuestion): ShuffledQuestion {
  const correctText = question.choices[question.correctAnswer - 1];
  const choices = [...question.choices];
  for (let i = choices.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [choices[i], choices[j]] = [choices[j], choices[i]]; }
  return { ...question, choices: choices as ExamQuestion["choices"], correctAnswer: choices.findIndex(item => item === correctText) + 1, originalCorrectAnswer: question.correctAnswer };
}

function FaceContent({ text, image, alt }: { text: string; image?: string; alt: string }) {
  const fallbackImage = /^https?:\/\//.test(text) ? text : undefined;
  const src = image || fallbackImage;
  const visibleText = fallbackImage ? "" : text;
  return <div className="flex min-h-0 flex-1 flex-col items-center justify-center gap-4 overflow-y-auto px-3 py-6 text-center">{src && <img src={src} alt={alt} className="max-h-44 max-w-full shrink-0 rounded-2xl object-contain shadow-sm sm:max-h-52" />}{visibleText && <p className="max-w-full break-words text-lg font-black leading-relaxed sm:text-2xl">{visibleText}</p>}</div>;
}

export function ExamTake() {
  const [, params] = useRoute("/subjects/:subjectId/exams/:examId/take"); const [, setLocation] = useLocation(); const search = useSearch();
  const { subjects, updateExam } = useStudyData(); const subject = subjects.find(x => x.id === params?.subjectId); const exam = subject?.exams.find(x => x.id === params?.examId); const from = new URLSearchParams(search).get("from");
  const flashcards: MediaFlashcard[] = subject && exam ? JSON.parse(localStorage.getItem(`studyhub:final-flashcards:${subject.id}:${exam.type}`) ?? "[]") : [];
  const makeItems = () => [...(exam?.questions ?? []).map(question => ({ kind: "question" as const, question: shuffleQuestion(question) })), ...flashcards.map(card => ({ kind: "flashcard" as const, card }))];
  const baseItems = useMemo(makeItems, [exam?.id, exam?.questions, subject?.id, exam?.type]);
  const [items, setItems] = useState<Item[]>(baseItems), [answers, setAnswers] = useState<Record<string, AnswerValue>>({}), [confirmed, setConfirmed] = useState<Record<string, boolean>>({}), [index, setIndex] = useState(0), [flipped, setFlipped] = useState(false), [seconds, setSeconds] = useState(0), [result, setResult] = useState<any>(null), [showMissed, setShowMissed] = useState(false), [sectionIntro, setSectionIntro] = useState<string | null>(null);
  useEffect(() => { if (result) return; const timer = window.setInterval(() => setSeconds(value => value + 1), 1000); return () => window.clearInterval(timer); }, [result]);
  if (!subject || !exam) return <div className="p-8 text-center text-muted-foreground">Exam not found</div>;
  const goBack = () => from ? setLocation(decodeURIComponent(from)) : window.history.length > 1 ? window.history.back() : setLocation(`/subjects/${subject.id}/lectures?type=${exam.type}`);
  if (!items.length) return <div className="mx-auto flex min-h-[70vh] max-w-xl items-center justify-center"><GlassCard className="w-full border-dashed border-2 bg-transparent p-10 text-center"><p className="text-xl font-bold">No exam content yet</p><button onClick={goBack} className="mt-5 rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground">Go back</button></GlassCard></div>;
  const item = items[index], key = item.kind === "question" ? item.question.id : item.card.id, progress = Math.round((index + 1) / items.length * 100), time = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  const missed = items.filter(entry => entry.kind === "question" ? Number(answers[entry.question.id] ?? 0) !== entry.question.correctAnswer : answers[entry.card.id] !== "known");
  const submit = () => { const questions = items.filter((entry): entry is Extract<Item, { kind: "question" }> => entry.kind === "question"); const qCorrect = questions.filter(entry => Number(answers[entry.question.id] ?? 0) === entry.question.correctAnswer).length; const flashPoints = flashcards.reduce((sum, card) => sum + (answers[card.id] === "known" ? 1 : answers[card.id] === "moderate" ? .5 : 0), 0); const total = questions.length + flashcards.length; const correct = qCorrect + flashPoints; const percentage = total ? Math.round(correct / total * 100) : 0; const score = { correct, total, percentage, takenAt: new Date().toISOString() }; updateExam(subject.id, exam.id, { lastScore: score, checked: percentage >= 70 }); setResult({ score, flashPoints }); };
  const next = () => { if (index >= items.length - 1) return submit(); const nextItem = items[index + 1], currentType = item.kind === "flashcard" ? "Flashcards" : item.question.questionType, nextType = nextItem.kind === "flashcard" ? "Flashcards" : nextItem.question.questionType; if (currentType !== nextType) { setSectionIntro(nextType); window.setTimeout(() => setSectionIntro(null), 700); } setIndex(value => value + 1); setFlipped(false); };
  const restart = (wrongOnly = false) => { setItems(wrongOnly ? missed : makeItems()); setAnswers({}); setConfirmed({}); setIndex(0); setSeconds(0); setResult(null); setShowMissed(false); setFlipped(false); };
  if (result) { const band = getScoreBand(result.score.percentage); return <div className="mx-auto max-w-3xl space-y-5 pb-24"><header className="flex items-center gap-3"><button onClick={goBack} className="flex h-11 w-11 items-center justify-center rounded-full border border-border bg-secondary"><ArrowLeft className="h-5 w-5" /></button><div><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Exam complete</p><h1 className="text-2xl font-bold">{exam.name}</h1></div></header><GlassCard className="p-7 text-center"><div className="mx-auto flex h-28 w-28 items-center justify-center rounded-full text-3xl font-black text-white" style={{ backgroundColor: band.color }}>{result.score.percentage}%</div><h2 className="mt-4 text-2xl font-bold">{band.label}</h2><p className="mt-2 font-semibold">Flashcards: {result.flashPoints} of {flashcards.length} points</p><p className="mt-1 text-sm text-muted-foreground">Know it = 1 · Moderate = 0.5 · Didn't know = 0</p></GlassCard><button onClick={() => setShowMissed(value => !value)} className="w-full rounded-2xl border border-border bg-card p-4 text-left"><b>Review items</b><p className="text-sm text-muted-foreground">{missed.length} need more work</p></button><AnimatePresence>{showMissed && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-3">{missed.map(entry => entry.kind === "question" ? <GlassCard key={entry.question.id} className="p-4"><b>{entry.question.text}</b></GlassCard> : <GlassCard key={entry.card.id} className="p-4"><FaceContent text={entry.card.front} image={entry.card.frontImage} alt="Question" /><div className="mt-3 border-t border-border/40 pt-4"><FaceContent text={entry.card.back} image={entry.card.backImage} alt="Answer" /></div></GlassCard>)}</motion.div>}</AnimatePresence><div className="grid grid-cols-3 gap-3"><button onClick={() => restart(false)} className="rounded-2xl bg-secondary py-4"><RotateCcw className="mx-auto" /></button><button onClick={() => restart(true)} className="rounded-2xl bg-primary/10 py-4 text-primary">Retry review</button><button onClick={goBack} className="rounded-2xl bg-primary py-4 text-primary-foreground">Done</button></div></div>; }
  return <div className="-mx-4 -mt-4 min-h-[calc(100vh-5rem)] bg-background px-4 pb-24 pt-4 md:-mx-6 md:px-6"><div className="mx-auto max-w-3xl space-y-4"><header className="flex items-center gap-3"><button onClick={goBack} className="flex h-11 w-11 items-center justify-center rounded-full border border-border bg-secondary"><ArrowLeft className="h-5 w-5" /></button><div className="min-w-0 flex-1"><p className="truncate text-lg font-bold">{exam.name}</p><p className="text-sm text-muted-foreground">Item {index + 1} of {items.length}</p></div><div className="flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-2 font-mono text-sm"><Clock3 className="h-4 w-4 text-primary" />{time}</div></header><div className="h-2 overflow-hidden rounded-full bg-secondary"><motion.div className="h-full rounded-full bg-primary" animate={{ width: `${progress}%` }} /></div><AnimatePresence>{sectionIntro && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="rounded-2xl bg-primary/10 p-4 text-center font-bold text-primary">{sectionIntro}</motion.div>}</AnimatePresence><AnimatePresence mode="wait"><motion.div key={key} initial={{ opacity: 0, x: 28 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -28 }} transition={transition}>{item.kind === "question" ? <QuestionView question={item.question} selected={Number(answers[item.question.id] ?? 0)} confirmed={!!confirmed[item.question.id]} onSelect={number => setAnswers(value => ({ ...value, [item.question.id]: number }))} /> : <FlashcardView card={item.card} flipped={flipped} onFlip={() => setFlipped(value => !value)} onMark={rating => { setAnswers(value => ({ ...value, [key]: rating })); next(); }} />}</motion.div></AnimatePresence>{item.kind === "question" && <div className="grid grid-cols-2 gap-3"><button disabled={index === 0} onClick={() => setIndex(value => value - 1)} className="rounded-2xl bg-secondary py-4 disabled:opacity-30"><ChevronLeft className="mx-auto" /></button>{confirmed[item.question.id] ? <button onClick={next} className="rounded-2xl bg-primary py-4 text-primary-foreground">Next<ChevronRight className="ml-2 inline" /></button> : <button disabled={!answers[item.question.id]} onClick={() => setConfirmed(value => ({ ...value, [item.question.id]: true }))} className="rounded-2xl bg-primary py-4 text-primary-foreground disabled:opacity-40">Check answer</button>}</div>}</div></div>;
}

function QuestionView({ question, selected, confirmed, onSelect }: { question: ShuffledQuestion; selected: number; confirmed: boolean; onSelect: (number: number) => void }) { return <GlassCard className="space-y-5 p-5"><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold uppercase text-primary">{question.questionType}</span>{question.questionType === "Medical Case MCQ" && (question.labs || question.histo) && <div className="rounded-2xl bg-secondary/30 p-4 text-sm">{question.labs && <p>Labs: {question.labs}</p>}{question.histo && <p>Histo: {question.histo}</p>}</div>}<h2 className="text-xl font-bold">{question.text}</h2><div className="space-y-3">{question.choices.map((choice, i) => { const n = i + 1, chosen = selected === n, correct = confirmed && n === question.correctAnswer, wrong = confirmed && chosen && !correct; return <button key={n} disabled={confirmed} onClick={() => onSelect(n)} className={`flex min-h-14 w-full items-center gap-3 rounded-2xl border-2 px-4 py-3 text-left ${correct ? "border-emerald-500 bg-emerald-500/10" : wrong ? "border-destructive bg-destructive/10" : chosen ? "border-primary bg-primary/10" : "border-border"}`}><span className="flex h-8 w-8 items-center justify-center rounded-full border font-bold">{String.fromCharCode(65 + i)}</span><span className="flex-1">{choice}</span>{correct && <Check />}{wrong && <X />}</button>; })}</div></GlassCard>; }

function FlashcardView({ card, flipped, onFlip, onMark }: { card: MediaFlashcard; flipped: boolean; onFlip: () => void; onMark: (rating: FlashRating) => void }) { return <div className="space-y-3"><div className="rounded-[2rem] bg-gradient-to-br from-primary/20 via-transparent to-primary/5 p-px shadow-xl" style={{ perspective: 1400 }}><motion.button onClick={onFlip} className="relative h-[min(22rem,52vh)] min-h-[17rem] w-full rounded-[2rem] text-left" animate={{ rotateY: flipped ? 180 : 0 }} transition={{ type: "spring", stiffness: 145, damping: 24, mass: .9 }} style={{ transformStyle: "preserve-3d" }}><div className="absolute inset-0 flex min-h-0 flex-col overflow-hidden rounded-[2rem] border border-border/50 bg-card p-6 sm:p-7" style={{ backfaceVisibility: "hidden" }}><div className="flex shrink-0 justify-between"><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">Front</span><Sparkles className="text-primary" /></div><FaceContent text={card.front} image={card.frontImage} alt="Question" /><p className="shrink-0 border-t border-border/40 pt-3 text-center text-xs text-muted-foreground">Tap to reveal</p></div><div className="absolute inset-0 flex min-h-0 flex-col overflow-hidden rounded-[2rem] border border-primary/25 bg-gradient-to-br from-primary/15 via-card to-card p-6 sm:p-7" style={{ backfaceVisibility: "hidden", transform: "rotateY(180deg)" }}><span className="w-fit shrink-0 rounded-full bg-primary px-3 py-1 text-xs font-bold text-primary-foreground">Back</span><FaceContent text={card.back} image={card.backImage} alt="Answer" /><p className="shrink-0 border-t border-border/40 pt-3 text-center text-xs text-muted-foreground">Choose your recall level</p></div></motion.button></div><AnimatePresence>{flipped && <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="grid grid-cols-3 gap-2"><button onClick={() => onMark("missed")} className="flex min-h-16 flex-col items-center justify-center rounded-2xl bg-destructive/10 px-1 text-xs font-semibold text-destructive sm:text-sm"><span>Didn't know</span><small className="mt-1 opacity-70">0 points</small></button><button onClick={() => onMark("moderate")} className="flex min-h-16 flex-col items-center justify-center rounded-2xl bg-amber-500/10 px-1 text-xs font-semibold text-amber-600 sm:text-sm"><span>Moderate</span><small className="mt-1 opacity-70">0.5 point</small></button><button onClick={() => onMark("known")} className="flex min-h-16 flex-col items-center justify-center rounded-2xl bg-primary px-1 text-xs font-semibold text-primary-foreground sm:text-sm"><span>Know it</span><small className="mt-1 opacity-80">1 point</small></button></motion.div>}</AnimatePresence></div>; }
