import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowLeft, Pencil, Plus, Trash2 } from "lucide-react";
import { useLocation, useRoute, useSearch } from "wouter";
import { ConfirmSheet } from "@/components/shared/ConfirmSheet";
import { GlassCard } from "@/components/shared/GlassCard";
import { useStudyData, type ExamQuestion, type Flashcard, type QuestionType } from "@/hooks/useStudyData";

type Tab = "flashcards" | "mcqs";
const inputCls = "w-full rounded-2xl border border-border/60 bg-secondary/40 px-4 py-3 text-sm outline-none transition-all duration-200 focus:border-primary/40 focus:ring-2 focus:ring-primary/20";
const panelMotion = { initial: { opacity: 0, x: 12 }, animate: { opacity: 1, x: 0 }, exit: { opacity: 0, x: -12 }, transition: { duration: .22, ease: [.4, 0, .2, 1] as const } };

export function FinalExamQuestions() {
  const [, params] = useRoute("/subjects/:subjectId/exams/:examId/questions"); const [, setLocation] = useLocation(); const search = useSearch();
  const { subjects, updateExam } = useStudyData(); const subject = subjects.find(x => x.id === params?.subjectId); const exam = subject?.exams.find(x => x.id === params?.examId); const from = new URLSearchParams(search).get("from");
  const [tab, setTab] = useState<Tab>("flashcards"); const [deleteTarget, setDeleteTarget] = useState<{ kind: Tab; id: string } | null>(null); const [editingId, setEditingId] = useState<string | null>(null);
  const [front, setFront] = useState(""), [back, setBack] = useState("");
  const [questionType, setQuestionType] = useState<QuestionType>("MCQ"), [text, setText] = useState(""), [choices, setChoices] = useState(["", "", "", ""]), [correct, setCorrect] = useState(1), [labs, setLabs] = useState(""), [histo, setHisto] = useState("");
  const flashKey = subject && exam ? `studyhub:final-flashcards:${subject.id}:${exam.type}` : "";
  const [flashcards, setFlashcards] = useState<Flashcard[]>(() => flashKey ? JSON.parse(localStorage.getItem(flashKey) ?? "[]") : []);
  const questions = exam?.questions ?? [];
  const goBack = () => from ? setLocation(decodeURIComponent(from)) : window.history.length > 1 ? window.history.back() : setLocation(`/subjects/${subject?.id}/lectures?type=${exam?.type}`);
  const saveFlashcards = (next: Flashcard[]) => { setFlashcards(next); localStorage.setItem(flashKey, JSON.stringify(next)); };
  const reset = () => { setEditingId(null); setFront(""); setBack(""); setQuestionType("MCQ"); setText(""); setChoices(["", "", "", ""]); setCorrect(1); setLabs(""); setHisto(""); };
  if (!subject || !exam) return <div className="p-8 text-center text-muted-foreground">Final Exam not found</div>;

  const saveFlashcard = () => { if (!front.trim() || !back.trim()) return; const next = editingId ? flashcards.map(x => x.id === editingId ? { ...x, front: front.trim(), back: back.trim() } : x) : [...flashcards, { id: crypto.randomUUID(), front: front.trim(), back: back.trim() }]; saveFlashcards(next); reset(); };
  const saveQuestion = () => { if (!text.trim() || choices.some(x => !x.trim())) return; const item: ExamQuestion = { id: editingId ?? crypto.randomUUID(), questionType, text: text.trim(), choices: choices as [string, string, string, string], correctAnswer: correct, labs: questionType === "Medical Case MCQ" ? labs.trim() || undefined : undefined, histo: questionType === "Medical Case MCQ" ? histo.trim() || undefined : undefined }; updateExam(subject.id, exam.id, { questions: editingId ? questions.map(x => x.id === editingId ? item : x) : [...questions, item] }); reset(); };
  const editFlashcard = (x: Flashcard) => { setTab("flashcards"); setEditingId(x.id); setFront(x.front); setBack(x.back); };
  const editQuestion = (x: ExamQuestion) => { setTab("mcqs"); setEditingId(x.id); setQuestionType(x.questionType); setText(x.text); setChoices([...x.choices]); setCorrect(x.correctAnswer); setLabs(x.labs ?? ""); setHisto(x.histo ?? ""); };
  const confirmDelete = () => { if (!deleteTarget) return; if (deleteTarget.kind === "flashcards") saveFlashcards(flashcards.filter(x => x.id !== deleteTarget.id)); else updateExam(subject.id, exam.id, { questions: questions.filter(x => x.id !== deleteTarget.id) }); setDeleteTarget(null); if (editingId === deleteTarget.id) reset(); };

  return <div className="mx-auto max-w-3xl space-y-5 pb-24">
    <header className="flex items-center gap-3"><button onClick={goBack} className="flex h-11 w-11 items-center justify-center rounded-full border border-border bg-secondary"><ArrowLeft className="h-5 w-5" /></button><div><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Final Exam</p><h1 className="text-2xl font-bold">Edit Questions</h1></div></header>
    <div className="grid grid-cols-2 gap-1 rounded-2xl border border-border/50 bg-secondary/40 p-1.5">{(["flashcards", "mcqs"] as Tab[]).map(x => <button key={x} onClick={() => { setTab(x); reset(); }} className={`min-h-11 rounded-xl font-semibold capitalize transition-all duration-200 ${tab === x ? "bg-card shadow-sm ring-1 ring-border/50" : "text-muted-foreground"}`}>{x === "mcqs" ? "MCQs" : "Flashcards"}</button>)}</div>
    <AnimatePresence mode="wait">
      {tab === "flashcards" ? <motion.section key="flashcards" {...panelMotion} className="space-y-4"><GlassCard className="space-y-3 p-4"><h2 className="font-bold">{editingId ? "Edit flashcard" : "Add flashcard"}</h2><input className={inputCls} value={front} onChange={e => setFront(e.target.value)} placeholder="Front face" /><textarea className={inputCls} value={back} onChange={e => setBack(e.target.value)} placeholder="Back face" /><button onClick={saveFlashcard} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-primary py-3.5 font-semibold text-primary-foreground"><Plus className="h-4 w-4" />{editingId ? "Save Flashcard" : "Add Flashcard"}</button></GlassCard><div className="space-y-3"><AnimatePresence>{flashcards.map(x => <motion.div key={x.id} layout initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0, height: 0 }}><GlassCard className="p-4"><div className="flex gap-3"><div className="min-w-0 flex-1"><p className="font-semibold">{x.front}</p><p className="mt-1 text-sm text-muted-foreground">{x.back}</p></div><button onClick={() => editFlashcard(x)} className="rounded-xl p-2 text-primary"><Pencil className="h-4 w-4" /></button><button onClick={() => setDeleteTarget({ kind: "flashcards", id: x.id })} className="rounded-xl p-2 text-destructive"><Trash2 className="h-4 w-4" /></button></div></GlassCard></motion.div>)}</AnimatePresence></div></motion.section> :
      <motion.section key="mcqs" {...panelMotion} className="space-y-4"><GlassCard className="space-y-3 p-4"><h2 className="font-bold">{editingId ? "Edit question" : "Add question"}</h2><div className="grid grid-cols-2 gap-2">{(["MCQ", "Medical Case MCQ"] as QuestionType[]).map(x => <button key={x} onClick={() => setQuestionType(x)} className={`rounded-xl border px-3 py-3 text-sm font-semibold ${questionType === x ? "border-primary bg-primary/10 text-primary" : "border-border"}`}>{x}</button>)}</div><textarea className={inputCls} value={text} onChange={e => setText(e.target.value)} placeholder="Question text" />{choices.map((choice, index) => <input key={index} className={inputCls} value={choice} onChange={e => setChoices(v => v.map((x, i) => i === index ? e.target.value : x))} placeholder={`Choice ${index + 1}`} />)}<select className={inputCls} value={correct} onChange={e => setCorrect(Number(e.target.value))}>{[1, 2, 3, 4].map(x => <option key={x} value={x}>Correct answer: Choice {x}</option>)}</select>{questionType === "Medical Case MCQ" && <><textarea className={inputCls} value={labs} onChange={e => setLabs(e.target.value)} placeholder="Labs (optional)" /><textarea className={inputCls} value={histo} onChange={e => setHisto(e.target.value)} placeholder="Histo (optional)" /></>}<button onClick={saveQuestion} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-primary py-3.5 font-semibold text-primary-foreground"><Plus className="h-4 w-4" />{editingId ? "Save Question" : "Add Question"}</button></GlassCard><div className="space-y-3"><AnimatePresence>{questions.map(x => <motion.div key={x.id} layout initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0, height: 0 }}><GlassCard className="p-4"><div className="flex gap-3"><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase text-primary">{x.questionType}</p><p className="mt-1 font-semibold">{x.text}</p></div><button onClick={() => editQuestion(x)} className="rounded-xl p-2 text-primary"><Pencil className="h-4 w-4" /></button><button onClick={() => setDeleteTarget({ kind: "mcqs", id: x.id })} className="rounded-xl p-2 text-destructive"><Trash2 className="h-4 w-4" /></button></div></GlassCard></motion.div>)}</AnimatePresence></div></motion.section>}
    </AnimatePresence>
    <ConfirmSheet isOpen={!!deleteTarget} onClose={() => setDeleteTarget(null)} onConfirm={confirmDelete} title="Remove this item?" message="This removes only the selected item from the Final Exam." confirmLabel="Remove Item" />
  </div>;
}
