import { useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { useLocation, useRoute } from "wouter";
import { ArrowLeft, Brain, ExternalLink, Layers, Link2, Save, Trash2, Upload, X } from "lucide-react";
import { useStudyData, type ExamQuestion, type StudyType } from "@/hooks/useStudyData";
import { parseExamExcel, parseFlashcardExcel } from "@/lib/excelImport";

export function LectureEdit() {
  const [, params] = useRoute("/subjects/:subjectId/lectures/:lectureId"); const [, setLocation] = useLocation();
  const { subjects, updateLecture, deleteLecture, addExam, updateExam, addFlashcard, deleteFlashcard } = useStudyData();
  const subject = subjects.find(s => s.id === params?.subjectId), lecture = subject?.lectures.find(l => l.id === params?.lectureId);
  const [sheet, setSheet] = useState<"flashcards" | "mcqs" | null>(null), [notice, setNotice] = useState("");
  const flashcardRef = useRef<HTMLInputElement>(null), mcqRef = useRef<HTMLInputElement>(null);
  const form = useForm({ defaultValues: { name: lecture?.name ?? "", link: lecture?.link ?? "" } });
  if (!subject || !lecture) return <div className="p-8 text-center text-muted-foreground">Lecture not found</div>;
  const lectureExam = subject.exams.find(e => e.linkedLectureIds?.includes(lecture.id)), flashcards = lecture.flashcards ?? [];
  const inputCls = "w-full rounded-2xl border border-border/60 bg-secondary/35 px-4 py-3.5 text-sm outline-none transition focus:border-primary/40 focus:ring-2 focus:ring-primary/20";
  const goBack = () => window.history.length > 1 ? window.history.back() : setLocation(`/subjects/${subject.id}/lectures?type=${lecture.type}`);
  const save = (data: { name: string; link: string }) => { updateLecture(subject.id, lecture.id, { name: data.name.trim(), link: data.link.trim() }); setNotice("Lecture details saved."); };
  const setType = (type: StudyType) => { updateLecture(subject.id, lecture.id, { type }); if (lectureExam) updateExam(subject.id, lectureExam.id, { type }); };
  const appendQuestions = (questions: ExamQuestion[]) => { if (lectureExam) updateExam(subject.id, lectureExam.id, { questions: [...(lectureExam.questions ?? []), ...questions] }); else addExam(subject.id, { name: `${lecture.name} MCQs`, link: "", grade: null, date: null, weight: 1, type: lecture.type, linkedLectureIds: [lecture.id], questions }); };

  return <div className="space-y-6 pb-24">
    <div className="rounded-[2rem] bg-gradient-to-br from-primary/35 via-border/70 to-border/40 p-[1px] shadow-xl">
      <div className="relative isolate overflow-hidden rounded-[calc(2rem-1px)] bg-card p-5">
        <div className="pointer-events-none absolute inset-3 overflow-hidden rounded-[1.55rem]"><div className="absolute -right-16 -top-16 h-52 w-52 rounded-full bg-primary/14 blur-3xl" /><div className="absolute -bottom-20 left-1/3 h-40 w-40 rounded-full bg-primary/5 blur-3xl" /></div>
        <div className="relative flex items-start gap-4">
          <button onClick={goBack} className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full border border-border/60 bg-background/75 shadow-sm"><ArrowLeft className="h-5 w-5" /></button>
          <div className="min-w-0 flex-1"><p className="text-xs font-black uppercase tracking-[0.2em] text-primary">Lecture settings</p><h1 className="mt-2 truncate text-3xl font-black tracking-tight">{lecture.name}</h1><p className="mt-2 text-sm capitalize text-muted-foreground">{subject.name} · {lecture.type}</p></div>
          <div className="shrink-0 rounded-2xl border border-border/60 bg-background/70 px-3 py-2 text-center shadow-sm"><p className="text-xl font-black">{lecture.readerLastPercentage ?? 0}%</p><p className="text-[9px] font-bold uppercase tracking-wider text-muted-foreground">mastered</p></div>
        </div>
      </div>
    </div>
    {notice && <div className="flex items-center justify-between rounded-2xl border border-border bg-secondary/40 px-4 py-3 text-sm"><span>{notice}</span><button onClick={() => setNotice("")}><X className="h-4 w-4" /></button></div>}
    <form onSubmit={form.handleSubmit(save)}><section className="rounded-3xl border border-border/60 bg-card p-5 shadow-sm"><p className="mb-4 text-xs font-black uppercase tracking-[0.18em] text-muted-foreground">Lecture information</p><div className="space-y-4"><div><label className="mb-2 block text-sm font-bold">Name</label><input {...form.register("name", { required: true })} className={inputCls} /></div><div><label className="mb-2 block text-sm font-bold">Link</label><div className="relative"><input {...form.register("link")} className={`${inputCls} pr-12`} placeholder="https://..." />{form.watch("link") && <a href={form.watch("link")} target="_blank" rel="noreferrer" className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-2 text-muted-foreground"><ExternalLink className="h-4 w-4" /></a>}</div></div><button className="flex w-full items-center justify-center gap-2 rounded-2xl bg-primary py-3.5 font-bold text-primary-foreground"><Save className="h-4 w-4" /> Save details</button></div></section></form>
    <section className="rounded-3xl border border-border/60 bg-card p-5 shadow-sm"><p className="mb-4 text-xs font-black uppercase tracking-[0.18em] text-muted-foreground">Lecture type</p><div className="grid grid-cols-2 gap-2 rounded-2xl bg-secondary/50 p-1.5">{(["theoretical", "practical"] as StudyType[]).map(item => <button key={item} onClick={() => setType(item)} className={`rounded-xl py-3 font-bold capitalize ${lecture.type === item ? "bg-background shadow-sm ring-1 ring-border/50" : "text-muted-foreground"}`}>{item}</button>)}</div></section>
    <section><p className="mb-3 text-xs font-black uppercase tracking-[0.18em] text-muted-foreground">Study content</p><div className="grid grid-cols-2 gap-3"><button onClick={() => setSheet("flashcards")} className="rounded-3xl border border-primary/20 bg-primary/10 p-5 text-left shadow-sm"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl border border-primary/20 bg-primary/15 text-primary"><Layers /></div><p className="text-lg font-black">Flashcards</p><p className="mt-1 text-sm text-muted-foreground">{flashcards.length} cards</p></button><button onClick={() => setSheet("mcqs")} className="rounded-3xl border border-primary/20 bg-primary/10 p-5 text-left shadow-sm"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl border border-primary/20 bg-primary/15 text-primary"><Brain /></div><p className="text-lg font-black">MCQs</p><p className="mt-1 text-sm text-muted-foreground">{lectureExam?.questions?.length ?? 0} questions</p></button></div></section>
    <button onClick={() => { if (confirm("Delete this lecture and its study content?")) { deleteLecture(subject.id, lecture.id); setLocation(`/subjects/${subject.id}/lectures?type=${lecture.type}`); } }} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-destructive/20 bg-destructive/5 py-3.5 font-bold text-destructive"><Trash2 className="h-4 w-4" /> Delete lecture</button>
    <input ref={flashcardRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={async e => { const file=e.target.files?.[0]; if(file){const {rows}=await parseFlashcardExcel(file); rows.forEach(row=>addFlashcard(subject.id,lecture.id,row)); setNotice(`Added ${rows.length} flashcards.`);} e.target.value=""; setSheet(null); }} />
    <input ref={mcqRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={async e => { const file=e.target.files?.[0]; if(file){const questions=await parseExamExcel(file); appendQuestions(questions); setNotice(`Added ${questions.length} MCQs.`);} e.target.value=""; setSheet(null); }} />
    {sheet && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 backdrop-blur-sm" onClick={() => setSheet(null)}><div className="w-full max-w-lg rounded-t-[2.5rem] border border-border bg-card px-5 pb-8 pt-3 text-foreground shadow-2xl" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-6 h-1.5 w-24 rounded-full bg-secondary" /><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-primary">{sheet === "mcqs" ? "MCQ bank" : "Flashcard deck"}</p><h2 className="mt-2 text-3xl font-black">{lecture.name}</h2><p className="mt-2 text-muted-foreground">{sheet === "mcqs" ? `${lectureExam?.questions?.length ?? 0} questions` : `${flashcards.length} cards`}</p></div><button onClick={()=>setSheet(null)} className="rounded-full bg-secondary p-3 text-muted-foreground"><X /></button></div><div className="mt-7 rounded-3xl border border-border bg-secondary/20 p-5"><p className="text-xs font-black uppercase tracking-widest text-muted-foreground">Actions</p><div className="mt-4 grid gap-3"><button onClick={()=>sheet === "mcqs" ? mcqRef.current?.click() : flashcardRef.current?.click()} className="flex items-center gap-4 rounded-2xl border border-border bg-card p-4 text-left"><Upload className="text-primary"/><div><p className="font-bold">Add more {sheet === "mcqs" ? "MCQs" : "flashcards"}</p><p className="text-sm text-muted-foreground">Import and keep existing content</p></div></button><button onClick={()=>{if(sheet === "mcqs" && lectureExam) updateExam(subject.id,lectureExam.id,{questions:[],lastScore:null,checked:false}); if(sheet === "flashcards") flashcards.forEach(card=>deleteFlashcard(subject.id,lecture.id,card.id)); setNotice(`All ${sheet === "mcqs" ? "MCQs" : "flashcards"} removed.`); setSheet(null);}} className="flex items-center gap-4 rounded-2xl border border-destructive/20 bg-destructive/5 p-4 text-left text-destructive"><Trash2/><div><p className="font-bold">Remove all</p><p className="text-sm opacity-60">Clear this complete collection</p></div></button><button onClick={()=>setLocation(sheet === "mcqs" ? (lectureExam?.questions?.length ? `/subjects/${subject.id}/exams/${lectureExam.id}/take` : `/subjects/${subject.id}/lectures/${lecture.id}`) : `/subjects/${subject.id}/lectures/${lecture.id}/study`)} className="flex items-center gap-4 rounded-2xl border border-primary/20 bg-primary/10 p-4 text-left text-primary"><Link2/><div><p className="font-bold">Study now</p><p className="text-sm opacity-60">Open the study experience</p></div></button></div></div></div></div>}
  </div>;
}