import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { useLocation, useRoute, useSearch } from "wouter";
import { ArrowLeft, BookOpen, Brain, Check, ChevronRight, File, FileQuestion, Image, Layers, Link as LinkIcon, Paperclip, Pencil, Plus, Trash2, Upload } from "lucide-react";
import { GlassCard } from "@/components/shared/GlassCard";
import { SwipeRow } from "@/components/shared/SwipeRow";
import { BottomSheet } from "@/components/shared/BottomSheet";
import { ConfirmSheet } from "@/components/shared/ConfirmSheet";
import { useStudyData, type Attachment, type AttachmentFormat, type Exam, type ExamQuestion, type StudyType } from "@/hooks/useStudyData";
import { parseExamExcel, parseFlashcardExcel, parseLectureExcel } from "@/lib/excelImport";
import { parseFinalExamFiles, type FinalExamImportError } from "@/lib/finalExamImport";

type Section = "progress" | "lectures" | "attachments";
type ImportRequest = null | { kind: "mcq" | "flashcards"; lectureId: string };
const sections: [Section, string][] = [["progress", "Progress"], ["lectures", "Lectures"], ["attachments", "Attachments"]];
const motionPanel = { initial: { opacity: 0, y: 8 }, animate: { opacity: 1, y: 0 }, exit: { opacity: 0, y: -8 }, transition: { duration: .2, ease: [.4, 0, .2, 1] as const } };
const examAccent = "hsl(280 67% 60%)";
const fromHere = () => `${window.location.pathname}${window.location.search}`;

function ActionTile({ icon: Icon, label, onClick }: { icon: any; label: string; onClick: () => void }) {
  return <button onClick={onClick} className="w-full min-h-24 rounded-2xl border-2 border-dashed border-border bg-secondary/20 p-4 text-muted-foreground transition-all duration-200 hover:border-primary/40 hover:bg-primary/5 hover:text-primary active:scale-[.99] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring motion-reduce:transform-none"><Icon className="mx-auto mb-2 h-5 w-5" /><span className="text-sm font-semibold">{label}</span></button>;
}
function attachmentIcon(a: Attachment) { if (a.format === "Image") return Image; if (/^https?:\/\//.test(a.url)) return LinkIcon; return File; }

export function SubjectStudyHub() {
  const [, nested] = useRoute("/subjects/:id/:section"); const [, base] = useRoute("/subjects/:id");
  const [location, setLocation] = useLocation(); const search = useSearch();
  const { subjects, addLecture, addExam, updateExam, updateSubject, addFlashcard, addAttachment, updateAttachment, deleteAttachment } = useStudyData();
  const id = nested?.id ?? base?.id; const subject = subjects.find(x => x.id === id); const raw = nested?.section as Section | undefined; const section = sections.some(([x]) => x === raw) ? raw! : "progress";
  const requestedType = new URLSearchParams(search).get("type"); const [lectureType, setLectureType] = useState<StudyType>(requestedType === "practical" ? "practical" : "theoretical");
  const [notice, setNotice] = useState(""); const [importRequest, setImportRequest] = useState<ImportRequest>(null); const [finalImportOpen, setFinalImportOpen] = useState(false); const [importing, setImporting] = useState(false); const [importErrors, setImportErrors] = useState<FinalExamImportError[]>([]);
  const lectureImportRef = useRef<HTMLInputElement>(null), questionImportRef = useRef<HTMLInputElement>(null), flashcardImportRef = useRef<HTMLInputElement>(null), finalImportRef = useRef<HTMLInputElement>(null);
  const [attachmentOpen, setAttachmentOpen] = useState(false), [editingAttachment, setEditingAttachment] = useState<Attachment | null>(null), [deletingAttachment, setDeletingAttachment] = useState<Attachment | null>(null);
  const [attachmentName, setAttachmentName] = useState(""), [attachmentUrl, setAttachmentUrl] = useState(""), [attachmentFormat, setAttachmentFormat] = useState<"Image" | "Link" | "File">("Link");
  const reviewedKey = `studyhub:reviewed-attachments:${id ?? "unknown"}`; const [reviewed, setReviewed] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem(reviewedKey) ?? "[]"); } catch { return []; } });
  useEffect(() => { if (id && location === `/subjects/${id}`) setLocation(`/subjects/${id}/progress`, { replace: true }); }, [id, location, setLocation]);
  useEffect(() => localStorage.setItem(reviewedKey, JSON.stringify(reviewed)), [reviewed, reviewedKey]);
  if (!subject) return <div className="p-8 text-center text-muted-foreground">Subject not found</div>;

  const lectures = subject.lectures.filter(x => x.type === lectureType), theoretical = subject.lectures.filter(x => x.type === "theoretical"), practical = subject.lectures.filter(x => x.type === "practical"), attachments = subject.attachments ?? [];
  const finalExam = subject.exams.find(x => x.type === lectureType && x.name === "Final Exam"); const finalFlashcardKey = `studyhub:final-flashcards:${subject.id}:${lectureType}`; const finalFlashcards = JSON.parse(localStorage.getItem(finalFlashcardKey) ?? "[]");
  const completedLectures = subject.lectures.filter(x => x.checked).length, completedExams = subject.exams.filter(x => x.checked || x.lastScore).length, reviewedCount = attachments.filter(x => reviewed.includes(x.id)).length, total = subject.lectures.length + subject.exams.length + attachments.length, overall = total ? Math.round((completedLectures + completedExams + reviewedCount) / total * 100) : 0;
  const lectureExam = (lectureId: string) => subject.exams.find(x => x.linkedLectureIds?.includes(lectureId));
  const changeType = (next: StudyType) => { setLectureType(next); setLocation(`/subjects/${subject.id}/lectures?type=${next}`, { replace: true }); };
  const importLectures = async (file?: File) => { if (!file) return; const { names, skipped } = await parseLectureExcel(file); names.forEach(name => addLecture(subject.id, { name, link: "", type: lectureType })); setNotice(`Imported ${names.length} lecture${names.length === 1 ? "" : "s"}${skipped ? `; skipped ${skipped}` : ""}.`); };
  const ensureFinalExam = (): Exam => { if (finalExam) return finalExam; const created: Exam = { id: crypto.randomUUID(), name: "Final Exam", link: "", grade: null, date: null, weight: 1, type: lectureType, linkedLectureIds: [], questions: [], lastScore: null, checked: false }; updateSubject(subject.id, { exams: [...subject.exams, created] }); return created; };
  const openFinalEdit = () => { const exam = ensureFinalExam(); setLocation(`/subjects/${subject.id}/exams/${exam.id}/edit?from=${encodeURIComponent(fromHere())}`); };
  const importFinalFiles = async (files: File[]) => { if (!files.length) return; setFinalImportOpen(false); setImporting(true); setImportErrors([]); try { const parsed = await parseFinalExamFiles(files); const exam = ensureFinalExam(); if (parsed.questions.length) updateExam(subject.id, exam.id, { questions: [...(exam.questions ?? []), ...parsed.questions] }); if (parsed.flashcards.length) localStorage.setItem(finalFlashcardKey, JSON.stringify([...finalFlashcards, ...parsed.flashcards])); setImportErrors(parsed.errors); const added = parsed.questions.length + parsed.flashcards.length; if (added) setNotice(`Imported ${parsed.questions.length} question${parsed.questions.length === 1 ? "" : "s"} and ${parsed.flashcards.length} flashcard${parsed.flashcards.length === 1 ? "" : "s"}.`); } finally { setImporting(false); } };
  const handleQuestionImport = async (file?: File) => { if (!file || !importRequest) return; setImporting(true); try { const questions: ExamQuestion[] = await parseExamExcel(file); const existing = lectureExam(importRequest.lectureId), lecture = subject.lectures.find(x => x.id === importRequest.lectureId); if (existing) updateExam(subject.id, existing.id, { questions: [...(existing.questions ?? []), ...questions] }); else addExam(subject.id, { name: `${lecture?.name ?? "Lecture"} MCQs`, link: "", grade: null, date: null, weight: 1, type: lecture?.type ?? lectureType, linkedLectureIds: [importRequest.lectureId], questions }); setNotice(`Imported ${questions.length} questions.`); setImportRequest(null); } finally { setImporting(false); } };
  const handleFlashcardImport = async (file?: File) => { if (!file || !importRequest) return; setImporting(true); try { const { rows, skipped } = await parseFlashcardExcel(file); rows.forEach(r => addFlashcard(subject.id, importRequest.lectureId, r)); setNotice(`Imported ${rows.length} flashcards${skipped ? `; skipped ${skipped}` : ""}.`); setImportRequest(null); } finally { setImporting(false); } };
  const openAttachment = (a: Attachment) => { setReviewed(v => v.includes(a.id) ? v : [...v, a.id]); window.open(a.url, "_blank", "noopener,noreferrer"); };
  const beginAddAttachment = () => { setEditingAttachment(null); setAttachmentName(""); setAttachmentUrl(""); setAttachmentFormat("Link"); setAttachmentOpen(true); };
  const beginEditAttachment = (a: Attachment) => { setEditingAttachment(a); setAttachmentName(a.name ?? ""); setAttachmentUrl(a.url); setAttachmentFormat(a.format === "Image" ? "Image" : /^https?:\/\//.test(a.url) ? "Link" : "File"); setAttachmentOpen(true); };
  const saveAttachment = () => { if (!attachmentName.trim() || !attachmentUrl.trim()) return; const payload = { name: attachmentName.trim(), url: attachmentUrl.trim(), type: "Study Sheet" as const, format: (attachmentFormat === "Image" ? "Image" : "File") as AttachmentFormat, priority: "Not Important" as const }; editingAttachment ? updateAttachment(subject.id, editingAttachment.id, payload) : addAttachment(subject.id, payload); setAttachmentOpen(false); setNotice(editingAttachment ? "Attachment updated." : "Attachment added."); };
  const ProgressRow = ({ label, done, count }: { label: string; done: number; count: number }) => { const value = count ? Math.round(done / count * 100) : 0; return <div className="rounded-2xl border border-border/50 bg-secondary/30 p-4"><div className="mb-3 flex justify-between"><div><p className="font-semibold">{label}</p><p className="text-xs text-muted-foreground">{done} of {count}</p></div><b>{value}%</b></div><div className="h-2 overflow-hidden rounded-full bg-secondary"><motion.div initial={{ width: 0 }} animate={{ width: `${value}%` }} className="h-full rounded-full bg-primary" /></div></div>; };

  return <div className="space-y-6 pb-24">
    <header className="flex items-center gap-3"><button onClick={() => setLocation("/subjects")} className="flex h-10 w-10 items-center justify-center rounded-full border border-border/50 bg-secondary/60"><ArrowLeft className="h-4 w-4" /></button><div><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Subject</p><h1 className="text-2xl font-bold md:text-3xl">{subject.emoji ?? "📚"} {subject.name}</h1></div></header>
    <nav className="scrollbar-hide overflow-x-auto rounded-2xl border border-border/50 bg-secondary/40 p-1.5"><div className="flex min-w-max gap-1 md:min-w-0">{sections.map(([key, label]) => <button key={key} onClick={() => setLocation(`/subjects/${subject.id}/${key}`)} className={`min-h-11 min-w-28 flex-1 rounded-xl px-4 text-sm font-semibold ${section === key ? "bg-card shadow-sm ring-1 ring-border/50" : "text-muted-foreground"}`}>{label}</button>)}</div></nav>
    {notice && <div className="rounded-xl border border-border bg-secondary/40 px-4 py-3 text-sm">{notice}</div>}
    {importErrors.length > 0 && <div className="rounded-xl border border-destructive/20 bg-destructive/10 px-4 py-3 text-sm text-destructive">{importErrors.map(error => <p key={`${error.filename}-${error.reason}`}><b>{error.filename}:</b> {error.reason}</p>)}</div>}
    <AnimatePresence>{importing && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: .2 }} className="rounded-xl border border-border bg-secondary/40 px-4 py-3 text-sm">Parsing selected files…</motion.div>}</AnimatePresence>
    <AnimatePresence mode="wait">
      {section === "progress" && <motion.section key="progress" {...motionPanel} className="space-y-4"><GlassCard className="p-6 text-center"><p className="text-4xl font-bold">{overall}%</p><p className="text-muted-foreground">Overall progress</p></GlassCard><div className="grid gap-3 md:grid-cols-2"><ProgressRow label="Theoretical lectures" done={theoretical.filter(x => x.checked).length} count={theoretical.length} /><ProgressRow label="Practical lectures" done={practical.filter(x => x.checked).length} count={practical.length} /><ProgressRow label="Exam attempts" done={completedExams} count={subject.exams.length} /><ProgressRow label="Attachments reviewed" done={reviewedCount} count={attachments.length} /></div></motion.section>}
      {section === "lectures" && <motion.section key="lectures" {...motionPanel} className="space-y-4"><div className="grid grid-cols-2 gap-1 rounded-2xl border border-border/50 bg-secondary/40 p-1.5">{(["theoretical", "practical"] as StudyType[]).map(x => <button key={x} onClick={() => changeType(x)} className={`min-h-11 rounded-xl font-semibold capitalize ${lectureType === x ? "bg-card shadow-sm ring-1 ring-border/50" : "text-muted-foreground"}`}>{x}</button>)}</div><FinalExamCard exam={finalExam} flashcardCount={finalFlashcards.length} subjectId={subject.id} type={lectureType} onImport={() => setFinalImportOpen(true)} onEdit={openFinalEdit} /><div className="grid gap-3 md:grid-cols-2">{lectures.map((lecture, index) => { const exam = lectureExam(lecture.id), mcqs = exam?.questions?.length ?? 0, cards = lecture.flashcards?.length ?? 0, from = encodeURIComponent(fromHere()); return <SwipeRow key={lecture.id} onTap={() => setLocation(`/subjects/${subject.id}/lectures/${lecture.id}?from=${from}`)} onSwipeLeft={() => mcqs ? setLocation(`/subjects/${subject.id}/exams/${exam!.id}/take?from=${from}`) : setImportRequest({ kind: "mcq", lectureId: lecture.id })} leftLabel={mcqs ? "Examine MCQs" : "Import MCQs"} leftIcon={Brain} leftColor="hsl(var(--primary))" onSwipeRight={() => cards ? setLocation(`/subjects/${subject.id}/lectures/${lecture.id}/study?from=${from}`) : setImportRequest({ kind: "flashcards", lectureId: lecture.id })} rightLabel={cards ? "Examine Flashcards" : "Import Flashcards"} rightIcon={Layers} rightColor="hsl(var(--primary))"><GlassCard className="p-4"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-border/50 bg-secondary/60 text-xs font-bold">{String(index + 1).padStart(2, "0")}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{lecture.name}</p><p className="mt-1 text-xs text-muted-foreground">{mcqs} MCQs · {cards} flashcards</p></div><ChevronRight className="h-4 w-4" /></div></GlassCard></SwipeRow>; })}</div>{!lectures.length && <GlassCard className="border-dashed border-2 bg-transparent p-10 text-center">No {lectureType} lectures yet.</GlassCard>}<div className="grid grid-cols-2 gap-3"><ActionTile icon={Plus} label="Add Lecture" onClick={() => addLecture(subject.id, { name: `New ${lectureType} lecture`, link: "", type: lectureType })} /><ActionTile icon={Upload} label="Import Lectures" onClick={() => lectureImportRef.current?.click()} /></div></motion.section>}
      {section === "attachments" && <motion.section key="attachments" {...motionPanel} className="space-y-4"><div><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Library</p><h2 className="text-xl font-bold">Subject attachments</h2></div>{attachments.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{attachments.map(a => { const Icon = attachmentIcon(a); return <SwipeRow key={a.id} onTap={() => openAttachment(a)} onSwipeLeft={() => beginEditAttachment(a)} leftLabel="Edit" leftIcon={Pencil} leftColor="hsl(var(--primary))" onSwipeRight={() => setDeletingAttachment(a)} rightLabel="Delete" rightIcon={Trash2} rightColor="hsl(var(--destructive))"><GlassCard className="p-4"><div className="flex items-start gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl border border-border/50 bg-secondary/60"><Icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{a.name || a.type}</p><p className="mt-1 text-xs text-muted-foreground">{a.format}</p></div>{reviewed.includes(a.id) && <Check className="h-4 w-4 text-primary" />}</div></GlassCard></SwipeRow>; })}</div> : <GlassCard className="border-dashed border-2 bg-transparent p-10 text-center"><Paperclip className="mx-auto mb-3" />No attachments yet.</GlassCard>}<ActionTile icon={Plus} label="Add Attachment" onClick={beginAddAttachment} /></motion.section>}
    </AnimatePresence>
    <input ref={lectureImportRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e => { importLectures(e.target.files?.[0]); e.target.value = ""; }} />
    <input ref={questionImportRef} type="file" accept=".xlsx,.xls" className="hidden" onChange={e => { handleQuestionImport(e.target.files?.[0]); e.target.value = ""; }} />
    <input ref={flashcardImportRef} type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={e => { handleFlashcardImport(e.target.files?.[0]); e.target.value = ""; }} />
    <input ref={finalImportRef} type="file" accept=".xlsx,.xls" multiple className="hidden" onChange={e => { importFinalFiles(Array.from(e.target.files ?? [])); e.target.value = ""; }} />
    <BottomSheet isOpen={!!importRequest} onClose={() => setImportRequest(null)} title={importRequest?.kind === "flashcards" ? "Import Flashcards" : "Import Questions"}><button disabled={importing} onClick={() => importRequest?.kind === "flashcards" ? flashcardImportRef.current?.click() : questionImportRef.current?.click()} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-primary py-4 font-semibold text-primary-foreground"><Upload className="h-5 w-5" />Import file</button></BottomSheet>
    <BottomSheet isOpen={finalImportOpen} onClose={() => setFinalImportOpen(false)} title="Import Final Exam content"><div className="space-y-3"><p className="text-sm text-muted-foreground">Select one or more Study Hub Exam or Flashcards spreadsheets.</p><button disabled={importing} onClick={() => finalImportRef.current?.click()} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-primary py-4 font-semibold text-primary-foreground disabled:opacity-50"><Upload className="h-5 w-5" />Import file</button></div></BottomSheet>
    <BottomSheet isOpen={attachmentOpen} onClose={() => setAttachmentOpen(false)} title={editingAttachment ? "Edit Attachment" : "Add Attachment"}><div className="space-y-4"><input value={attachmentName} onChange={e => setAttachmentName(e.target.value)} placeholder="Name" className="w-full rounded-xl border border-border bg-background px-4 py-3" /><input value={attachmentUrl} onChange={e => setAttachmentUrl(e.target.value)} placeholder="Link" className="w-full rounded-xl border border-border bg-background px-4 py-3" /><div className="grid grid-cols-3 gap-2">{(["Image", "Link", "File"] as const).map(x => <button key={x} onClick={() => setAttachmentFormat(x)} className={`rounded-xl border px-3 py-3 font-semibold ${attachmentFormat === x ? "border-primary bg-primary/10 text-primary" : "border-border"}`}>{x}</button>)}</div><button onClick={saveAttachment} className="w-full rounded-xl bg-primary py-3.5 font-semibold text-primary-foreground">{editingAttachment ? "Save Changes" : "Add Attachment"}</button></div></BottomSheet>
    <ConfirmSheet isOpen={!!deletingAttachment} onClose={() => setDeletingAttachment(null)} onConfirm={() => { if (deletingAttachment) { deleteAttachment(subject.id, deletingAttachment.id); setDeletingAttachment(null); } }} title="Delete attachment?" message="This removes the attachment card and its link from this subject." confirmLabel="Delete Attachment" />
  </div>;
}

function FinalExamCard({ exam, flashcardCount, subjectId, type, onImport, onEdit }: { exam?: Exam; flashcardCount: number; subjectId: string; type: StudyType; onImport: () => void; onEdit: () => void }) {
  const [, setLocation] = useLocation(); const count = exam?.questions?.length ?? 0, total = count + flashcardCount, from = encodeURIComponent(fromHere());
  return <SwipeRow onTap={onEdit} onSwipeRight={onEdit} rightLabel="Edit" rightIcon={FileQuestion} rightColor={examAccent} onSwipeLeft={() => total && exam ? setLocation(`/subjects/${subjectId}/exams/${exam.id}/take?from=${from}`) : onImport()} leftLabel={total ? "Examine" : "Add Questions"} leftIcon={BookOpen} leftColor={examAccent}><GlassCard className="overflow-hidden bg-card p-0"><div className="h-1" style={{ backgroundColor: examAccent }} /><div className="p-5"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-purple-500/20 bg-purple-500/10 text-purple-500"><FileQuestion /></div><div className="flex-1"><p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Pinned · {type}</p><h3 className="mt-1 text-lg font-bold">Final Exam</h3><p className="mt-1 text-xs text-muted-foreground">{count} questions · {flashcardCount} flashcards</p></div><ChevronRight className="h-4 w-4" /></div></div></GlassCard></SwipeRow>;
}
